# -*- coding: utf-8 -*-
"""Untitled1 (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RFqq5EYSVXOPGybc75d5YoHNTqeQrKL
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/creditcard.csv")

df.head()

print(df.info())
print(df['Class'].value_counts())

df.isnull().sum()

df = df.drop_duplicates()

len(df)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler=StandardScaler()
df[['Time', 'Amount']] = scaler.fit_transform(df[['Time', 'Amount']])

feature= df.drop(columns=['Class'])
target = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    feature, target, test_size=0.2, random_state=42, stratify=target
)

X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

import joblib

joblib.dump(scaler,"scaler.pkl")

import os
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

X_train = pd.read_csv("X_train.csv")
X_test = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv").squeeze()
y_test = pd.read_csv("y_test.csv").squeeze()

X_train.shape

X_test.shape

y_train.shape

y_test.shape

X_normal = X_train[y_train == 0]

X_normal.shape

model = IsolationForest(
    n_estimators=400,
    contamination=0.008,
    max_samples=0.8,
    max_features=1.0,
    random_state=42)
model.fit(X_normal)

joblib.dump(model, "model_forest.pkl")

pred = model.predict(X_test)
pred_labels = np.where(pred == -1, 1, 0)

print("Confusion Matrix:\n", confusion_matrix(y_test, pred_labels))
print("\nClassification Report:\n", classification_report(y_test, pred_labels, digits=4))

auc_score = roc_auc_score(y_test, pred_labels)
print(f"ROC-AUC Score: {auc_score:.4f}")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc

import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, pred_labels)
roc_auc = auc(fpr, tpr)
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], 'r--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()