# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcYEzxjWqdEw2QovQlnOxmw5_KUWi7_Z
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/creditcard.csv")

df.head()

print(df.info())
print(df['Class'].value_counts())

df.isnull().sum()

df = df.drop_duplicates()

len(df)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler=StandardScaler()
df[['Time', 'Amount']] = scaler.fit_transform(df[['Time', 'Amount']])

feature= df.drop(columns=['Class'])
target = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    feature, target, test_size=0.2, random_state=42, stratify=target
)

X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

import joblib

joblib.dump(scaler,"scaler.pkl")

import os
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

X_train = pd.read_csv("X_train.csv")
X_test = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv").squeeze()
y_test = pd.read_csv("y_test.csv").squeeze()

X_train.shape

X_test.shape

y_train.shape

y_test.shape

X_normal = X_train[y_train == 0]

X_normal.shape

Model = IsolationForest(
    n_estimators=200,
    contamination=0.0017,
    random_state=42,
    n_jobs=-1
)
Model.fit(X_normal)

joblib.dump(Model, "model_forest.pkl")

pred = Model.predict(X_test)
pred_labels = np.where(pred == -1, 1, 0)

print("Confusion Matrix:\n", confusion_matrix(y_test, pred_labels))
print("\nClassification Report:\n", classification_report(y_test, pred_labels, digits=4))

auc_score = roc_auc_score(y_test, pred_labels)
print(f"ROC-AUC Score: {auc_score:.4f}")